# version: '3.9'

services:
  mongo:
    image: mongo:5.0.2
    restart: 'unless-stopped'
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminvotepat
      MONGO_INITDB_ROOT_PASSWORD: TlW1WnLlxhnPxISQ
    volumes:
      - mongodb_typescript_backend_toolkit:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_typescript_backend_toolkit:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres.geifwkmjrthkhreivloa
      POSTGRES_PASSWORD: JXk6SPED0RRqMhO7
      POSTGRES_DB: postgres
    ports:
      - 6543
      # - 5432:5432
    volumes:
      - postgres_typescript_backend_toolkit:/var/lib/postgresql/data

  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres.geifwkmjrthkhreivloa
  #     POSTGRES_PASSWORD: JXk6SPED0RRqMhO7
  #     POSTGRES_DB: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres_typescript_backend_toolkit:/var/lib/postgresql/data

volumes:
  mongodb_typescript_backend_toolkit:
    external: true
  redis_typescript_backend_toolkit:
    external: true
  postgres_typescript_backend_toolkit:
    external: true
